version: '3.8'
services:
  # Load balancer front-end
  nginx:
    image: nginx:alpine
    ports:
      - "5000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-app
      - python-app
  
  # Aplicación Node.js
  node-app:
    build: ./mi-app-node
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
  
  # Aplicación Python
  python-app:
    build: ./mi-app-python
    expose:
      - "3000"
    environment:
      - FLASK_ENV=production

  # Base de datos compartida
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

volumes:
  redis-data:
