---
- name: Ensure Python3 is installed
  package:
    name: python3
    state: present

- name: Create application directory
  ansible.builtin.file:
    path: /home/myapp
    state: directory
    mode: '0755'

- name: Copy example app script
  copy:
    src: server.py
    dest: /home/myapp/server.py
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: Run example app
  shell: "nohup python3 /home/myapp/server.py &"
  args:
    chdir: /home/myapp
